version: '3.9'

services:
    portainer:
        mssql:
            image: 'mcr.microsoft.com/mssql/server'
            container_name: '${MSSQL_CONTAINER_NAME}'
            ports:
                - '${MSSQL_PORT}:1433'
            restart: always
            environment:
                - ACCEPT_EULA=${ACCEPT_EULA}
                - SA_PASSWORD=${SA_PASSWORD}
            volumes:
                - './drive:/var/opt/mssql'
